services:
  - {name: 'server1', ip: '10.0.1.31'}
  - {name: 'server2', ip: '10.0.1.148'}
  - {name: 'server3', ip: '10.0.1.33'}
  - {name: 'server4', ip: '10.0.1.34'}
  - {name: 'server5', ip: '10.0.1.35'}
  - {name: 'server6', ip: '10.0.1.36'}
